spring:
  application:
    name: currency-exchange-service
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
server:
  port: 8000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

